@startuml

!pragma layout smetana

class Overview{}
class MainMenu{}
class StartMenu{}
class CardMenu{}
class Menu{}
class CardDeck{}
class Card{}
class Game{}
class GameController{}
class Player{}
class Team{}
class Role{}
class Disease{}


Overview --* Menu
MainMenu --* Menu
StartMenu --* Menu
CardMenu --* Menu



Menu --* GameController


GameController *-- Game
Game *-- Disease
Game *-- CardDeck
Game *-- Team
CardDeck *-- Card
Team *-- Player
Player *-- Role



@enduml